#
###################################
# Site wide configuration
####################################
#
title: YOUN's
email: tnwk09@gmail.com
description: A simple and awesome blog.
url: # https://renyuanz.github.io/leonids # the base hostname & protocol for your site
keywords: ["Programming", "JAVA", "SQL", "WEB"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         :title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: YOUN's
#  avatar: leonids-logo.png
  job: "JAVA & WEB DEVELOPER"
#  bio: "A backend developer who loves design awesome things. Working for RendezvousCheznous atm in Marseille, France."
  email: tnwk09@gmail.com
#  disqus-shortname: renyuanzblog
#  twitter: renyuan814 #username
  facebook: tnwk09@gmail.com #username
  google:
    plus: #username
    analytics: #UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: lsy09 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
#  linkedin: renyuan-zou-69b7038a #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
